spring:
  datasource:
    url: jdbc:postgresql://database:5432/saltmerch
    username: jensenyh
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
